apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  namespace: todo
  labels:
    app: java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: java
        image: shubhamshinde2206/java:tag
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: java-service
spec:
  selector:
    app: java
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
