name: CI-pipeline

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'k8s/**'            # Ignore changes in the 'k8s' directory
      - 'README.md'
      - 'docs.md'
   
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'  # Adjust this version as needed

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: '8.0'  # Adjust this version as needed

    - name: Build with Gradle
      run: |
       ./gradlew dependencies
       ./gradlew clean
       ./gradlew build 

    - name: Publish to Nexus
      run: ./gradlew publish --info
      env:
        nexusUsername: ${{ secrets.NEXUS_USERNAME }}
        nexusPassword: ${{ secrets.NEXUS_PASSWORD }}   

  docker-push:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/java:${{ github.run_id }}

  update-newtag-in-github-repo:
    runs-on: ubuntu-latest
    needs: docker-push
    steps:
    - name: Checkout the manifest repository
      uses: actions/checkout@v4

    - name: Update tag in repo
      run: | 
        sed -i 's|shubhamshinde2206/java:.*|shubhamshinde2206/java:${{ github.run_id }}|' k8s/java.yml

    - name: Commit and push changes
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        git config --global user.email "shubham.ssc100@gmail.com"
        git config --global user.name "shubham9511s"
        git add k8s/java.yml
        git commit -m "Update tag in repo"
        git push 
