name: CI-pipeline

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'k8s/**'            # Ignore changes in the 'k8s' directory
      - 'README.md'
      - 'docs.md'
   
jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt' # Distribution to use (adopt, zulu, etc.)
        java-version: '17' # Java version to set up

    - name: Build with Gradle
      run: ./gradlew clean build --refresh-dependencies --stacktrace --info

    - name: Install SonarQube Scanner
      run: npm install -g sonarqube-scanner

    - name: Run SonarQube Scanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        ./gradlew sonarqube \
          -Dsonar.projectKey=java-app \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.java.binaries=.

  push:
    runs-on: ubuntu-latest
    needs: build-and-scan
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/java:${{ github.run_id }}

  publish-to-nexus:
    runs-on: ubuntu-latest
    needs: push
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt' # Distribution to use (adopt, zulu, etc.)
        java-version: '17' # Java version to set up

    - name: Publish to Nexus
      run: ./gradlew publish
      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        NEXUS_URL: ${{ secrets.NEXUS_URL }}

  update-newtag-in-github-repo:
    runs-on: ubuntu-latest
    needs: publish-to-nexus
    steps:
    - name: Checkout the manifest repository
      uses: actions/checkout@v4

    - name: Update tag in repo
      run: | 
        sed -i 's|shubhamshinde2206/java:.*|shubhamshinde2206/java:${{ github.run_id }}|' k8s/java.yml

    - name: Commit and push changes
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        git config --global user.email "shubham.ssc100@gmail.com"
        git config --global user.name "shubham9511s"
        git add k8s/java.yml
        git commit -m "Update tag in repo"
        git push 
